INSERT INTO EC.ART50 (MRZ,VALID_FROM) 
VALUES (510,TO_DATE('01-01-2017','dd-mm-yyyy'));

UPDATE
	(SELECT 
		VALID_FROM AS vf,
		LEAD(VALID_FROM,1) OVER (ORDER BY VALID_FROM)-1 AS vt
	FROM EC.ART50) tmp
SET VALID_TILL = tmp.vt
WHERE tmp.VALID_FROM = tmp.vf;


UPDATE EC.ART50
EC.ART50
WITH x AS (SELECT 
		VALID_FROM AS vf,
		LEAD(VALID_FROM,1) OVER (ORDER BY VALID_FROM)-1 AS vt
	FROM EC.ART50)
SELECT vt FROM x WHERE vf >1;
