SELECT * FROM FINANCE.CC_CONTRAGENTS
WHERE LEGAL_NAME LIKE '%ARENA%'

SUNFOODS BULGARIA EOOD 09 BOYANA BGR

INSERT INTO FINANCE.CC_CONTRAGENTS (LEGAL_NAME, CONTRAGENT_COL, ID_CONTRAGENT)
VALUES ('KINO ARENA BULGARIA EOOD SOFIA BGR', 'KINO', 76)

SELECT * FROM FINANCE.CC_CREDIT_CARD
WHERE "date_time" > TO_DATE('2019-03-25', 'YYYY-MM-DD');

SELECT * FROM FINANCE.CC_CLASSIFIER
WHERE ID_CONTRAGENT >= 341
AND ID_CONTRAGENT<350;