UPDATE CARS.FUEL
SET CARS.FUEL.MILEAGE = (SELECT mlg_NEW
                                  FROM CARS.FUEL_MILEAGE 
                                  WHERE CARS.FUEL.ID_FUEL = CARS.FUEL_MILEAGE.ID_FUEL)
        WHERE EXISTS (SELECT CARS.FUEL_MILEAGE.ID_FUEL
                        FROM CARS.FUEL_MILEAGE 
                        WHERE CARS.FUEL.ID_FUEL = CARS.FUEL_MILEAGE.ID_FUEL);
                        
SELECT 
    ID_CAR,
    DATE_FUEL,
    LAG (KM,1) OVER (PARTITION BY ID_CAR ORDER BY DATE_FUEL DESC) AS next_refuel,
    LAG (KM,1) OVER (PARTITION BY ID_CAR ORDER BY DATE_FUEL DESC) - DATE_FUEL AS diff
FROM FUEL
ORDER BY DATE_FUEL DESC;

SELECT 
    s.FUEL_NAME,
    dt.DRIVE_TYPE,
    c.DKN,
    SUM(AMOUNT),
    SUM(MILEAGE),
    ROUND(SUM(AMOUNT)/SUM(MILEAGE)*100,2) AS CONS
FROM CARS.FUEL
JOIN CARS.SUPPLIER_FUELS s ON s.ID_BRAND = CARS.FUEL.ID_BRAND
JOIN CARS.DRIVE_TYPE dt ON dt.ID_DRIVE_TYPE = CARS.FUEL.ID_DRIVE_TYPE
JOIN CARS.CARS c ON c.ID_CAR = CARS.FUEL.ID_CAR
GROUP BY s.FUEL_NAME, dt.DRIVE_TYPE, c.DKN
ORDER BY SUM(AMOUNT) DESC;
                       