--Verify of there are duplicates
--SELECT
--	DESCRIPTION
--	,COMPLETED_DATE
--	,PAID_IN_EUR
--	,PAID_OUT_EUR
--	,BALANCE_EUR 
--	,COUNT(*) 
--	FROM PRE_REVOLUT pr2 
--	GROUP BY DESCRIPTION, COMPLETED_DATE,PAID_IN_EUR , PAID_OUT_EUR, BALANCE_EUR
--	HAVING COUNT(*) >1 
--	ORDER BY COUNT(*) DESC

---remove existing
    DELETE FROM 
        PRE_REVOLUT
    WHERE ID IN (SELECT ID FROM DC_REVOLUT);

--- Insert the new records from the pre to the prod table
INSERT INTO DC_REVOLUT (ID, COMPLETED_DATE, DESCRIPTION, PAID_OUT_EUR, PAID_IN_EUR,EXCHANGE_OUT,EXCHANGE_IN,BALANCE_EUR,CATEGORY,NOTES)

SELECT
	ID
	,COMPLETED_DATE
	,DESCRIPTION 
	,TO_NUMBER(REPLACE(PAID_OUT_EUR, ',')) AS PAID_OUT_EUR
	,TO_NUMBER(REPLACE(PAID_IN_EUR, ',')) AS PAID_IN_EUR 
	,EXCHANGE_OUT 
	,EXCHANGE_IN 
	,TO_NUMBER(REPLACE(BALANCE_EUR, ',')) AS BALANCE_EUR 
	,CATEGORY 
	,NOTES 
	FROM PRE_REVOLUT pr ORDER BY COMPLETED_DATE DESC

---remove the transferred
    DELETE FROM 
        PRE_REVOLUT
    WHERE ID IN (SELECT ID FROM DC_REVOLUT);

--- Select unique records only
SELECT
	ID
	,COMPLETED_DATE
	,DESCRIPTION 
	,PAID_OUT_EUR 
	,PAID_IN_EUR 
	,EXCHANGE_OUT 
	,EXCHANGE_IN 
	,BALANCE_EUR 
	,CATEGORY 
	,NOTES 
	FROM PRE_REVOLUT pr 
WHERE ID NOT IN (
				SELECT ID FROM (
								SELECT 
									ROW_NUMBER() OVER (PARTITION BY DESCRIPTION
																	,COMPLETED_DATE
																	,PAID_IN_EUR
																	,PAID_OUT_EUR
																	,BALANCE_EUR  ORDER BY DESCRIPTION, ID)  AS r,
																	ID
									FROM PRE_REVOLUT pr3
									ORDER BY COMPLETED_DATE DESC
								) a
				WHERE a.r > 1
				)
ORDER BY COMPLETED_DATE DESC, ID

--- View detais for the duplicate records
--SELECT 
--	ROW_NUMBER() OVER (PARTITION BY DESCRIPTION
--									,COMPLETED_DATE
--									,PAID_IN_EUR
--									,PAID_OUT_EUR
--									,BALANCE_EUR  ORDER BY DESCRIPTION, ID)  AS r
--	,ID
--	,COMPLETED_DATE
--	,DESCRIPTION
--	,PAID_OUT_EUR 
--	,PAID_IN_EUR
--	,BALANCE_EUR
--	FROM PRE_REVOLUT pr3
--	ORDER BY COMPLETED_DATE DESC
