SELECT * FROM FINANCE.CC_CONTRAGENTS WHERE ID_CONTRAGENT IN (
SELECT DISTINCT ID_CONTRAGENT FROM FINANCE.CC_CONTRAGENTS
MINUS
SELECT DISTINCT ID_CONTRAGENT FROM FINANCE.CC_CLASSIFIER );

INSERT INTO FINANCE.CC_CLASSIFIER
(ID_CONTRAGENT, ID_TYPE, ID_CLASSIFICATION)
SELECT DISTINCT ID_CONTRAGENT, ID_TYPE, ID_CLASSIFICATION FROM FINANCE.CC_CONTRAGENTS WHERE ID_CONTRAGENT = 337;

UPDATE FINANCE.CC_CONTRAGENTS
SET FINANCE.CC_CONTRAGENTS.ID_CLASSIFICATION =  FINANCE.CC_CLASSIFIER.ID_CLASSIFICATION
INNER JOIN FINANCE.CC_CLASSIFIER 
ON FINANCE.CC_CLASSIFIER.ID_CONTRAGENT = FINANCE.CC_CONTRAGENTS.ID_CONTRAGENT 
WHERE ID_CONTRAGENT = 337;

UPDATE 
(SELECT FINANCE.CC_CONTRAGENTS.ID_CLASSIFICATION  as class_OLD, FINANCE.CC_CLASSIFIER.ID_CLASSIFICATION as NEW
 FROM FINANCE.CC_CONTRAGENTS
 INNER JOIN FINANCE.CC_CLASSIFIER
 ON FINANCE.CC_CLASSIFIER.ID_CONTRAGENT = FINANCE.CC_CONTRAGENTS.ID_CONTRAGENT
 WHERE FINANCE.CC_CLASSIFIER.ID_CONTRAGENT=102
) t

SET t.class_OLD = t.NEW;

UPDATE 
(SELECT FINANCE.CC_CONTRAGENTS.ID_TYPE  as OLD, FINANCE.CC_CLASSIFIER.ID_TYPE as NEW
 FROM FINANCE.CC_CONTRAGENTS
 INNER JOIN FINANCE.CC_CLASSIFIER
 ON FINANCE.CC_CLASSIFIER.ID_CONTRAGENT = FINANCE.CC_CONTRAGENTS.ID_CONTRAGENT
 WHERE FINANCE.CC_CLASSIFIER.ID_CONTRAGENT IN (SELECT DISTINCT ID_CONTRAGENT FROM FINANCE.CONTRAGENTS_EMP)
) type
SET type.OLD = type.NEW